// Product API Routes
### Get all contacts
GET http://localhost:3000/products

### Get product by id
GET http://localhost:3000/products/6a0b06e8cd235188acdd3798

### Create a new product
POST http://localhost:3000/products
content-type: application/json

{
    "itemCode": "APZ123",
    "itemDescription": "Tungsten Electrode",
    "brand": "No Brand",
    "price": 1000,
    "itemType": "Consumable"
}

### Update a product
PUT http://localhost:3000/products/6a0c565908c3a714c54d9cde
content-type: application/json

{
    "itemCode": "APZ123",
    "itemDescription": "Tungsten Electrode 2.4x150mm Red",
    "brand": "No Brand",
    "price": 1001,
    "itemType": "Consumable"
}

### Delete a product
DELETE http://localhost:3000/products/6a0c565908c3a714c54d9cde

// ============================================================================
// ============================================================================

//Supplier API Routes
### Get all suppliers
GET http://localhost:3000/suppliers

### Get supplier by id
GET http://localhost:3000/suppliers/6a0b0745cd235188acdd379a

### Create a new supplier
POST http://localhost:3000/suppliers
content-type: application/json

{
    "supplierName": "Tayan Electrical Supply",
    "supplierAddress": "Quezon City",
    "supplierTelephone": "02-8732-1254",
    "supplierPersonel": "Joy"
}

### Update a supplier
PUT http://localhost:3000/suppliers/6a0c6164de20b7750ee1c9a9
content-type: application/json

{
    "supplierName": "Tayan Electrical Supply",
    "supplierAddress": "Mandaluyong City",
    "supplierTelephone": "02-8732-1254",
    "supplierPersonel": "Joy"
}

### Delete a product
DELETE http://localhost:3000/suppliers/6a0c5b89f4676c91802261e6

